/**
 * E2E tests for lockfile parsing — real lockfile content parsing
 * for both package-lock.json and yarn.lock formats.
 */
import { describe, it, expect, vi } from 'vitest';

vi.mock('vscode', () => ({
  window: { showErrorMessage: vi.fn() },
  workspace: { workspaceFolders: [] },
  ProgressLocation: { Notification: 15 },
}));

import { parseLockfileDeps } from '../../dependencyMirrorManager';

describe('Lockfile Parsing E2E', () => {
  describe('package-lock.json v1 format', () => {
    it('parses a realistic package-lock.json v1', () => {
      const lockfile = JSON.stringify({
        name: 'my-project',
        version: '1.0.0',
        lockfileVersion: 1,
        dependencies: {
          'lodash': { version: '4.17.21', resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz' },
          'express': { version: '4.18.2', resolved: 'https://registry.npmjs.org/express/-/express-4.18.2.tgz' },
          'body-parser': { version: '1.20.2' },
          '@types/node': { version: '20.11.0' },
        },
      });

      const deps = parseLockfileDeps(lockfile, 'package-lock');
      expect(deps).toHaveLength(4);
      expect(deps.find(d => d.name === 'lodash')?.version).toBe('4.17.21');
      expect(deps.find(d => d.name === 'express')?.version).toBe('4.18.2');
      expect(deps.find(d => d.name === '@types/node')?.version).toBe('20.11.0');
    });
  });

  describe('package-lock.json v3 format', () => {
    it('parses a realistic package-lock.json v3 with packages field', () => {
      const lockfile = JSON.stringify({
        name: 'my-project',
        version: '1.0.0',
        lockfileVersion: 3,
        packages: {
          '': { name: 'my-project', version: '1.0.0' },
          'node_modules/lodash': { version: '4.17.21', resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz' },
          'node_modules/react': { version: '18.2.0' },
          'node_modules/react-dom': { version: '18.2.0' },
          'node_modules/@fortawesome/fontawesome-free': { version: '6.5.1' },
        },
      });

      const deps = parseLockfileDeps(lockfile, 'package-lock');
      expect(deps).toHaveLength(4); // root entry excluded
      expect(deps.find(d => d.name === 'lodash')?.version).toBe('4.17.21');
      expect(deps.find(d => d.name === 'react')?.version).toBe('18.2.0');
      expect(deps.find(d => d.name === '@fortawesome/fontawesome-free')?.version).toBe('6.5.1');
    });
  });

  describe('yarn.lock format', () => {
    it('parses a realistic yarn.lock', () => {
      const lockfile = [
        '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
        '# yarn lockfile v1',
        '',
        '',
        'lodash@^4.17.0:',
        '  version "4.17.21"',
        '  resolved "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"',
        '  integrity sha512-abc123',
        '',
        'express@^4.18.0:',
        '  version "4.18.2"',
        '  resolved "https://registry.npmjs.org/express/-/express-4.18.2.tgz"',
        '  integrity sha512-def456',
        '',
        'typescript@^5.3.0:',
        '  version "5.3.3"',
        '  resolved "https://registry.npmjs.org/typescript/-/typescript-5.3.3.tgz"',
        '',
      ].join('\n');

      const deps = parseLockfileDeps(lockfile, 'yarn-lock');
      expect(deps).toHaveLength(3);
      expect(deps.find(d => d.name === 'lodash')?.version).toBe('4.17.21');
      expect(deps.find(d => d.name === 'express')?.version).toBe('4.18.2');
      expect(deps.find(d => d.name === 'typescript')?.version).toBe('5.3.3');
    });
  });

  describe('edge cases', () => {
    it('handles empty package-lock.json', () => {
      const lockfile = JSON.stringify({ lockfileVersion: 1, dependencies: {} });
      const deps = parseLockfileDeps(lockfile, 'package-lock');
      expect(deps).toHaveLength(0);
    });

    it('handles empty yarn.lock', () => {
      const lockfile = '# yarn lockfile v1\n\n';
      const deps = parseLockfileDeps(lockfile, 'yarn-lock');
      expect(deps).toHaveLength(0);
    });

    it('handles package-lock.json with no dependencies field', () => {
      const lockfile = JSON.stringify({ lockfileVersion: 1 });
      const deps = parseLockfileDeps(lockfile, 'package-lock');
      expect(deps).toHaveLength(0);
    });
  });
});
